### 1. Load Dataset

In [1]:
import pandas as pd

df = pd.read_csv('dataHospital.csv')
df.head()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
0,1110053,RS Arun Lhokseumawe,Aceh,Kota Lhokseumawe,Jl. Plaju Komplek Perumahan PT Arun Batuphat T...,Rumah Sakit Umum,C,Non BLU/BLUD,SWASTA/LAINNYA,218,218,328,36,328
1,1106014,RS Umum Fandika,Aceh,Aceh Tengah,Jl. Terminal Simpang Wariji Blangkolak 1 Kec. ...,Rumah Sakit Umum,D,Non BLU/BLUD,SWASTA/LAINNYA,45,45,45,15,45
2,1171110,RS Umum Daerah Meuraxa,Aceh,Kota Banda Aceh,Jl. Soekarno Hatta Km. 2 Desa Mibo Kecamatan B...,Rumah Sakit Umum,B,BLUD,Pemkot,310,310,487,77,487
3,1171163,RS Gigi Mulut Universitas Syiah Kuala,Aceh,Kota Banda Aceh,Jl. Prof A. Madjid Ibrahim I No. 5 Banda Aceh ...,Rumah Sakit Khusus Gigi dan Mulut,B,BLU,Kementerian Lain,11,11,182,24,0
4,1102027,RS Umum Daerah Kota Subulussalam,Aceh,Kota Subulussalam,Jl. Hamzah Fansyuri (Subulussalam-Rundeng) Kec...,Rumah Sakit Umum,C,BLUD,Pemkot,189,189,537,34,537

In [2]:
df.tail()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
3150,9232011,RS Umum Daerah Er Dabi,Papua Pegunungan,Yalimo,Jl. Trans Wamena Jayapura KM. 123 Heahobak Dis...,Rumah Sakit Umum,D,Non BLU/BLUD,Pemkab,35,35,182,18,0
3151,9231002,RS Umum Daerah Lukas Enembe Kab. Memberamo Tengah,Papua Pegunungan,Mamberamo Tengah,"Jln. Poros Gimbis Nomor 1, Distrik Kobakma, Ka...",Rumah Sakit Umum,D PRATAMA,Non BLU/BLUD,Pemkab,85,85,47,23,47
3152,9201046,RS Tk. IV 17.07.01 Jenderal LB Moerdani,Papua Selatan,Merauke,"Jl. Poros L.B. Moerdani, Kel. Kamangi, Kec. Ta...",Rumah Sakit Umum,D,Non BLU/BLUD,TNI AD,81,81,182,24,0
3153,9212027,RS TNI AD Tk. IV Timika,Papua Tengah,Mimika,Jl. Agimuga Mile 32 Desa Karang Senang Distrik...,Rumah Sakit Umum,D,Non BLU/BLUD,TNI AD,60,60,182,43,0
3154,9271023,RS Umum Abepura,Papua,Kota Jayapura,"Jl. Kesehatan No. I Abepura, jayapura",Rumah Sakit Umum,C,BLUD,Pemprop,236,236,190,79,190

### 2. Informasi Data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3155 entries, 0 to 3154
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         3155 non-null   int64
 1   nama                       3155 non-null   object
 2   propinsi                   3155 non-null   object
 3   kab                        3155 non-null   object
 4   alamat                     3155 non-null   object
 5   jenis                      3155 non-null   object
 6   kelas                      3155 non-null   object
 7   status_blu                 3155 non-null   object
 8   kepemilikan                3155 non-null   object
 9   median_total_tempat_tidur  3155 non-null   int64
 10  total_tempat_tidur         3155 non-null   int64
 11  median_total_tenaga        3155 non-null   int64
 12  total_layanan              3155 non-null   int64
 13  total_tenaga_kerja         3155 non-null   int64
dtypes: int64(6), object(8)
memory usage: 345.2+ KB

### 3. Struktur Data

In [4]:
# Melihat kolom pada dataframe
df.columns

Index(['id', 'nama', 'propinsi', 'kab', 'alamat', 'jenis', 'kelas',
       'status_blu', 'kepemilikan', 'median_total_tempat_tidur',
       'total_tempat_tidur', 'median_total_tenaga', 'total_layanan',
       'total_tenaga_kerja'],
      dtype='object')

In [5]:
# Menghitung jumlah baris dan kolom
df.shape

(3155, 14)

In [6]:
# Melihat tipe data pada kolom
df.dtypes

id                            int64
nama                         object
propinsi                     object
kab                          object
alamat                       object
jenis                        object
kelas                        object
status_blu                   object
kepemilikan                  object
median_total_tempat_tidur     int64
total_tempat_tidur            int64
median_total_tenaga           int64
total_layanan                 int64
total_tenaga_kerja            int64
dtype: object

### 4. Statistik Deskriptif

In [7]:
df.describe()

,id,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
count,3.155000e+03,3155.000000,3155.000000,3155.000000,3155.000000,3155.000000
mean,3.803327e+06,135.918859,135.433914,282.574643,41.097306,261.980666
std,2.005303e+06,550.885676,550.960235,372.457767,30.583893,382.352731
min,1.101015e+06,2.000000,0.000000,1.000000,1.000000,0.000000
25%,3.171859e+06,55.000000,54.000000,95.500000,22.000000,56.500000
50%,3.325039e+06,102.000000,102.000000,182.000000,31.000000,153.000000
75%,5.103046e+06,155.000000,155.000000,335.000000,50.000000,335.000000
max,9.271080e+06,30343.000000,30343.000000,7939.000000,419.000000,7939.000000

In [8]:
# untuk kolom numerik dan non numerik
df.describe(include='all')

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
count,3.155000e+03,3155,3155,3155,3155,3155,3155,3155,3155,3155.000000,3155.000000,3155.000000,3155.000000,3155.000000
unique,NaN,3085,38,511,3155,17,8,7,22,NaN,NaN,NaN,NaN,NaN
top,NaN,RS Umum Bunda,Jawa Timur,Kota Surabaya,Jl. Plaju Komplek Perumahan PT Arun Batuphat T...,Rumah Sakit Umum,C,Non BLU/BLUD,SWASTA/LAINNYA,NaN,NaN,NaN,NaN,NaN
freq,NaN,4,432,64,1,2648,1710,2335,869,NaN,NaN,NaN,NaN,NaN
mean,3.803327e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.918859,135.433914,282.574643,41.097306,261.980666
std,2.005303e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550.885676,550.960235,372.457767,30.583893,382.352731
min,1.101015e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,0.000000,1.000000,1.000000,0.000000
25%,3.171859e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.000000,54.000000,95.500000,22.000000,56.500000
50%,3.325039e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.000000,102.000000,182.000000,31.000000,153.000000
75%,5.103046e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155.000000,155.000000,335.000000,50.000000,335.000000
max,9.271080e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30343.000000,30343.000000,7939.000000,419.000000,7939.000000

In [9]:
df['median_total_tenaga'].mean()

np.float64(282.5746434231379)

In [10]:
df['median_total_tenaga'].median()

np.float64(182.0)

In [11]:
# Menggunakan varians untuk mengukur seberapa jauh data menyebar dari rata-rata
df['median_total_tenaga'].std()

np.float64(372.45776665652016)

In [12]:
df['median_total_tenaga'].sem()

np.float64(6.63097442702849)

### BoxPlot

In [13]:
df['median_total_tenaga'].max()

np.int64(7939)

In [14]:
df['median_total_tenaga'].min()

np.int64(1)

In [15]:
df['median_total_tenaga'].quantile(0.25)

np.float64(95.5)

In [16]:
df['median_total_tenaga'].quantile(0.5)

np.float64(182.0)

In [17]:
df['median_total_tenaga'].quantile(0.75)

np.float64(335.0)

### 5. Seleksi Akses Data

In [18]:
# Mengambil 5 baris diawal pada kolom tertentu
df.loc[0:4, ['nama', 'kelas']]

                                    nama kelas
0                    RS Arun Lhokseumawe     C
1                        RS Umum Fandika     D
2                 RS Umum Daerah Meuraxa     B
3  RS Gigi Mulut Universitas Syiah Kuala     B
4       RS Umum Daerah Kota Subulussalam     C

In [19]:
# Mengambil 5 baris diakhir pada kolom tertentu
df.loc[df.index[-5:], ['nama', 'kelas']]

                                                   nama      kelas
3150                             RS Umum Daerah Er Dabi          D
3151  RS Umum Daerah Lukas Enembe Kab. Memberamo Tengah  D PRATAMA
3152            RS Tk. IV 17.07.01 Jenderal LB Moerdani          D
3153                            RS TNI AD Tk. IV Timika          D
3154                                    RS Umum Abepura          C

### 6. Filtering Data

In [20]:
# Mengambil data yang hanya di propinsi DKI Jakarta
df_Jakarta = df[df['propinsi'] == 'DKI Jakarta']
df_Jakarta.head()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
738,3173084,RS Tk. II M. Ridwan Meuraksa,DKI Jakarta,Kota Jakarta Timur,Jl. Taman Mini I RT 004 / RW 02 Kel. Pinangran...,Rumah Sakit Umum,B,BLU,TNI AD,251,251,435,34,435
739,3172765,RS Ibu dan Anak AL-Fauzan,DKI Jakarta,Kota Jakarta Timur,RSIA Al Fauzan Jl. Pedati No. 3 Kel. Kampung T...,Rumah Sakit Khusus Ibu dan Anak,C,Non BLU/BLUD,SWASTA/LAINNYA,41,41,13,23,13
740,3171574,RS Umum Prikasih,DKI Jakarta,Kota Jakarta Selatan,"Jl. RS Fatmawati Raya No. 74, Pondok Labu, Cil...",Rumah Sakit Umum,C,Non BLU/BLUD,Organisasi Sosial,111,111,221,72,221
741,3173671,RS Gigi dan Mulut FKG Univ. Indonesia,DKI Jakarta,Kota Jakarta Pusat,Jl. Salemba Raya No. 4 Jakarta Pusat,Rumah Sakit Khusus Gigi dan Mulut,A,Non BLU/BLUD,Kementerian Lain,15,15,600,22,600
742,3171768,RS Umum Murni Teguh Sudirman Jakarta,DKI Jakarta,Kota Jakarta Pusat,Jl. Jend. Sudirman No. 86,Rumah Sakit Umum,C,Non BLU/BLUD,SWASTA/LAINNYA,114,114,205,79,205

In [21]:
# Mengambil data yang hanya total tempat tidur lebih dari 100
df_rumahSakitBesar = df[df['median_total_tempat_tidur'] > 100]
df_rumahSakitBesar.head()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
0,1110053,RS Arun Lhokseumawe,Aceh,Kota Lhokseumawe,Jl. Plaju Komplek Perumahan PT Arun Batuphat T...,Rumah Sakit Umum,C,Non BLU/BLUD,SWASTA/LAINNYA,218,218,328,36,328
2,1171110,RS Umum Daerah Meuraxa,Aceh,Kota Banda Aceh,Jl. Soekarno Hatta Km. 2 Desa Mibo Kecamatan B...,Rumah Sakit Umum,B,BLUD,Pemkot,310,310,487,77,487
4,1102027,RS Umum Daerah Kota Subulussalam,Aceh,Kota Subulussalam,Jl. Hamzah Fansyuri (Subulussalam-Rundeng) Kec...,Rumah Sakit Umum,C,BLUD,Pemkot,189,189,537,34,537
5,1106013,RS Umum Daerah Datu Beru Takengon,Aceh,Aceh Tengah,Jl. Rumah Sakit No.153 Kec. Kebayakan,Rumah Sakit Umum,B,BLUD,Pemkab,376,376,470,80,470
6,1109028,RS Umum Mufid,Aceh,Pidie,"JL. PROF. A. MAJID IBRAHIM, NO. 62-66, KEC. KO...",Rumah Sakit Umum,D,Non BLU/BLUD,Perusahaan,102,102,208,64,208

In [22]:
# Mengambil data yang hanya di propinsi DKI Jakarta dan total tempat tidur lebih dari 100
df_filter = df[(df['propinsi'] == 'DKI Jakarta') & (df['median_total_tempat_tidur'] > 100)]
df_filter.head()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
738,3173084,RS Tk. II M. Ridwan Meuraksa,DKI Jakarta,Kota Jakarta Timur,Jl. Taman Mini I RT 004 / RW 02 Kel. Pinangran...,Rumah Sakit Umum,B,BLU,TNI AD,251,251,435,34,435
740,3171574,RS Umum Prikasih,DKI Jakarta,Kota Jakarta Selatan,"Jl. RS Fatmawati Raya No. 74, Pondok Labu, Cil...",Rumah Sakit Umum,C,Non BLU/BLUD,Organisasi Sosial,111,111,221,72,221
742,3171768,RS Umum Murni Teguh Sudirman Jakarta,DKI Jakarta,Kota Jakarta Pusat,Jl. Jend. Sudirman No. 86,Rumah Sakit Umum,C,Non BLU/BLUD,SWASTA/LAINNYA,114,114,205,79,205
743,3174508,RS Pondok Indah Puri Indah,DKI Jakarta,Kota Jakarta Barat,"Jl. Puri Indah Raya,Blok S-2,Kel.Kembangan Sel...",Rumah Sakit Umum,B,Non BLU/BLUD,SWASTA/LAINNYA,200,200,247,102,247
744,3172516,RS Umum Kartika Pulo Mas,DKI Jakarta,Kota Jakarta Timur,Jl. Pulo Mas Timur K No 2 Jakarta Timur,Rumah Sakit Umum,C,Non BLU/BLUD,Organisasi Sosial,140,140,272,53,272

In [26]:
# Mengambil data yang hanya di propinsi DKI Jakarta dan total tenaga kerja kurang dari 10
df_filter_RumahSakitKecil = df[(df['propinsi'] == 'DKI Jakarta') & (df['median_total_tenaga'] < 10)]
df_filter_RumahSakitKecil.head()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
801,3175418,RS Umum Tzu Chi Hospital,DKI Jakarta,Kota Jakarta Utara,"Jl. Pantai Indah Kapuk Boulevard, Kel. Kamal ...",Rumah Sakit Umum,B,Non BLU/BLUD,Organisasi Budha,136,136,1,36,1

In [27]:
# Mengambil data untuk menampilkan baris dengan kolom kelas bernilai A atau B
df_kelas = df[df['kelas'].isin(['A', 'B'])]
df_kelas.head()

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
2,1171110,RS Umum Daerah Meuraxa,Aceh,Kota Banda Aceh,Jl. Soekarno Hatta Km. 2 Desa Mibo Kecamatan B...,Rumah Sakit Umum,B,BLUD,Pemkot,310,310,487,77,487
3,1171163,RS Gigi Mulut Universitas Syiah Kuala,Aceh,Kota Banda Aceh,Jl. Prof A. Madjid Ibrahim I No. 5 Banda Aceh ...,Rumah Sakit Khusus Gigi dan Mulut,B,BLU,Kementerian Lain,11,11,182,24,0
5,1106013,RS Umum Daerah Datu Beru Takengon,Aceh,Aceh Tengah,Jl. Rumah Sakit No.153 Kec. Kebayakan,Rumah Sakit Umum,B,BLUD,Pemkab,376,376,470,80,470
12,1110075,RS Umum Daerah Dr. Fauziah Bireun,Aceh,Bireuen,Jl. Mayjen T. Hamzah Bendahara No. 13 Bireuen,Rumah Sakit Umum,B,BLUD,Pemkab,251,251,1178,84,1178
14,1103010,RS Umum Daerah Dr. H. Yulidin Away,Aceh,Aceh Selatan,Jl. T. Ben Mahmud Nomor 86 A Tapaktuan,Rumah Sakit Umum,B,BLUD,Pemkab,359,359,515,68,515

In [28]:
# Mengambil data kolom jenis mengandung nilai Jantung
df[df['jenis'].str.contains('Jantung')]

,id,nama,propinsi,kab,alamat,jenis,kelas,status_blu,kepemilikan,median_total_tempat_tidur,total_tempat_tidur,median_total_tenaga,total_layanan,total_tenaga_kerja
834,3171912,RS Jantung dan Pembuluh Darah Heartology,DKI Jakarta,Kota Jakarta Selatan,"Jl. Birah III No. 4 Kel. Rawa Barat, Kebayoran...",Rumah Sakit Khusus Jantung,C,Non BLU/BLUD,SWASTA/LAINNYA,31,31,182,33,0
844,3174282,RS Jantung dan Pembuluh Darah Harapan Kita,DKI Jakarta,Kota Jakarta Barat,"Jl. S. Parman Kav 87, Slipi",Rumah Sakit Khusus Jantung,A,BLU,Kemkes,403,403,2458,52,2458
856,3172752,RS Jantung Binawaluya,DKI Jakarta,Kota Jakarta Timur,"Jl. TB Simatupang No.71, RT.11/RW.5, Susukan, ...",Rumah Sakit Khusus Jantung,C,Non BLU/BLUD,Perusahaan,21,21,82,42,82
893,3172755,RS Jantung Jakarta,DKI Jakarta,Kota Jakarta Timur,"Jl. Matraman Raya No. 23, RT 002 RW 001, Jakar...",Rumah Sakit Khusus Jantung,B,Non BLU/BLUD,Perusahaan,81,81,233,50,233
979,3208061,RS Jantung Hasna Medika Kuningan,Jawa Barat,Kuningan,Jl. Raya Cigugur Lingkungan Manis RT. 030 RW. ...,Rumah Sakit Khusus Jantung,B,Non BLU/BLUD,Perusahaan,75,75,134,33,134
1113,3273558,RS Jantung dan Pembuluh Darah Paramarta,Jawa Barat,Kota Bandung,Jl. Soekarno Hatta No. 581 Bandung 42075,Rumah Sakit Khusus Jantung,C,Non BLU/BLUD,Perusahaan,31,31,182,45,0
1155,3274136,RS Jantung Hasna Medika,Jawa Barat,Cirebon,"Jl. Raden Gilap No 8 Palimanan, Kabupaten Cirebon",Rumah Sakit Khusus Jantung,B,Non BLU/BLUD,SWASTA/LAINNYA,75,75,184,42,184
1311,3273560,RS Khusus Jantung dan Pembuluh Darah Melinda C...,Jawa Barat,Kota Bandung,"Jl. Dr. Cipto No. 11, RT 004 RW 002 Kel. Pasi...",Rumah Sakit Khusus Jantung,C,Non BLU/BLUD,SWASTA/LAINNYA,31,31,182,45,0
1330,3276150,RS Jantung Diagram,Jawa Barat,Kota Depok,Jl. Cinere Raya No.19,Rumah Sakit Khusus Jantung,B,Non BLU/BLUD,Perusahaan,75,75,191,47,191
1340,3278094,RS Jantung dan Pembuluh Darah Tasikmalaya,Jawa Barat,Kota Tasikmalaya,"Jl. Moch. Hatta, Kp. Kalangsari RT.001/RW.020,...",Rumah Sakit Khusus Jantung,B,Non BLU/BLUD,Perusahaan,76,76,182,47,0
2870,7371449,RS Otak & Jantung Pertamina Royal Biringkanaya,Sulawesi Selatan,Kota Makassar,Jl. Pajjaiang Sudiang Raya,Rumah Sakit Khusus Jantung,B,Non BLU/BLUD,BUMN,87,87,182,52,0
2966,7471136,RS Jantung dan Pembuluh Darah Oputa Yi Koo Sul...,Sulawesi Tenggara,Kota Kendari,Jl. Dr. Sam Ratulangi No. 151,Rumah Sakit Khusus Jantung,B,BLUD,Pemprop,132,132,182,55,0